### ISSUE TITLE
Support for multiline code blocks

### ISSUE THREAD

**Issue by tregusti** [rhysd/vim-gfm-syntax#2]
I would really like to have support for multiline code blocks from `gfm`. Like these:

    ```
    var thing;
    thing = 9;
    ```

And of course it would be really good to support language highlights within the code blocks based on the language tag:

    ```js
    var thing;
    thing = 9;
    ```
And markdown:

    ```md
    # Hello
    This is some text.
    ```

I would have helped if I knew more vimscript...

**Comment by rhysd** [comment]
Official `markdown` syntax supports highlighting code blocks. So vim-gfm-syntax need not to support it.

Please try below in your .vimrc.

```vim
autocmd FileType markdown hi link markdownCode Constant
```

Note that `Constant` is just a example. You can choose your favorite color from `:hi`.

**Comment by tregusti** [comment]
Thank you for answering. I know code block support is supported, what is not however if support for parsing the `js` or `md` suffix after the code block start.

What I would like to have is that the code below would be highlighted with the javascript syntax, within the markdown file that contains it. Just like github does when adding code blocks with a language hint.

    ```js
    var i = 0;
    ```

Is that possible to accomplish?

**Comment by tregusti** [comment]
I found that it too was built into https://github.com/tpope/vim-markdown.

`let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']`

Thank you for helping!

**Comment by rhysd** [comment]
@tregusti 

I also found that official syntax file looks to support it! I also didn't know.

```vim
let g:markdown_fenced_languages = ['javascript=js']
```

https://github.com/vim/vim/blob/master/runtime/syntax/markdown.vim#L21

Thank you for reporting this :smile:

**Comment by tregusti** [comment]
Yes, but it does not support fenced language highlight when using `~~~` it seems...

Not sure if you added support for the tilde blocks or if that is built into vim. If it is in vim by default, I'll open an issue about it there.

**Comment by rhysd** [comment]
Hmm... I need to consider more. Thanks anyway.
