### ISSUE TITLE
multi-line list continuation is not a code block

### ISSUE THREAD

**Issue by powerman** [rhysd/vim-gfm-syntax#4]
Is it possible to avoid highlighting multi-line list items of level 2+ as code blocks? Example:

```
- level1
  continuation
  - level2
    continuation
    - level3
      continuation

      more level3
      continuation

    more level2
    continuation

break list

    code
    block
```

- level1
  continuation
  - level2
    continuation
    - level3
      continuation

      more level3
      continuation

    more level2
    continuation

break list

    code
    block

**Comment by rhysd** [comment]
This plugin is only adding extra syntax highlight. So basic highlight is done by Vim's standard `runtime/syntax/markdown.vim`. So please make an issue for it in [maintenance repository](https://github.com/tpope/vim-markdown).

Please try to reproduce the issue without vim-gfm-syntax. If it can be reproducible, it's not related to vim-gfm-syntax.

**Comment by powerman** [comment]
You right, sorry.
