### ISSUE TITLE
Does not see shortcut reference links

### ISSUE THREAD

**Issue by rwxrob** [rhysd/vim-gfm-syntax#6]
https://github.github.com/gfm/#shortcut-reference-link

**Comment by rhysd** [comment]
What is not working? And what are you expecting? Please describe. I cannot understand only from the link.

**Comment by rwxrob** [comment]
It's fine I hacked mine. Yours is not recognizing shortcut reference links in text at all.

```markdown
This is a [short cut link] to something.

[short cut link]: http://google.com
```

**Comment by rhysd** [comment]
Thank you for additional description.

Is it a spec only for GFM? Or official commonmark spec? If it's only for GFM, this plugin would support it. But if it is an official commonmark spec, it should be supported by Vim's standard `markdown` syntax highlight.

**Comment by rhysd** [comment]
I tried http://spec.commonmark.org/dingus/.

It seems that it's a commonmark spec. So it should be supported by Vim standard markdown syntax highlight. This plugin just extends standard highlights for GFM specific features.

**Comment by rwxrob** [comment]
As I listed in my first post (the IRI there), this is part of the official GFM spec. In fact, it is *only* in the GFM spec.

**Comment by rhysd** [comment]
No, actually it is in commonmark spec. Please read http://spec.commonmark.org/0.28/#link-reference-definitions

**Comment by rwxrob** [comment]
Wow, happy to stand corrected. Must not be supported then by the standard vim markdown syntax (which isn't surprising). I went the tpope's because he had better linkref section (not just all red) and tweeked it to work with simplified. The real problem is simply that non of the specs—including CommonMark—are really specs at all. If you are interested I am working on [BaseML], a simplification of CommonMark that can be represented in IETF standard ABNF that should play much more nicely with, well, everything.

Thanks for looking at this.

[BaseML]: http://knowledgenet.io/concept/baseml/
