### ISSUE TITLE
Use only for github markdown

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [rhysd/vim-gfm-syntax#9]
Hey I like you plugin and I think you may be interested in the way I load it.

```viml
" Check if repository
" If yes change to github flavored markdown
function! s:CheckIfGithub()
    let cwd = getcwd()
    let parent_dir = expand('%:p:h')
    exe 'cd ' . parent_dir
	let github = system('git remote show origin | grep "Push  URL" | grep "github.com/" | wc -l')
    exe 'cd ' . cwd
	" if in a git repo
	if !v:shell_error
        if github > 0
            packadd vim-gfm-syntax
            let g:markdown_fenced_languages = ['cpp', 'ruby', 'json']
        endif
    elseif exists(g:gfm_syntax_enable_always)
        unlet g:gfm_syntax_enable_always
	endif
endfunction

autocmd BufEnter * call s:CheckIfGithub()

```

This basically just checks if the git repository, of the parent directory of the working file, pushes to a github.com url and if so use vim-gfm-syntax for all markdown, if url is not being sent to a github.com url or not in a git repository at all then nothing happens.

To the best of my knowledge this should allow vim-gfm-syntax to only and always be loaded when working with markdown for github and never for markdown files for anything else.

**Comment by rhysd** [comment]
Calling `system()` has a bit higher cost because it does exec for shell command. I don't want to block syntax highilghting as much as possible because it blocks loading buffer.

I think a logic like you showed should be written in `.vimrc` following the user's preference. In the case, I think there should be a way to enable/disable this plugin's highlighting per buffer. Do you think `b:gfm_syntax_enable` (it's buffer-local version of `g:gfm_syntax_enable_always`) is userful for your use case?

**Comment by rhysd** [comment]
I think `g:gfm_syntax_enable_filetypes` might be useful:

```vim
" Check if repository
" If yes change to github flavored markdown
function! s:CheckIfGithub()
    let cwd = getcwd()
    let parent_dir = expand('%:p:h')
    exe 'cd ' . parent_dir
    let github = system('git remote show origin | grep "Push  URL" | grep "github.com/" | wc -l')
    exe 'cd ' . cwd
    " if in a git repo
    if !v:shell_error && github > 0
        packadd vim-gfm-syntax
        set filetype=markdown.github
    else
        set filetype=markdown
    endif
endfunction

autocmd BufNew,BufRead *.md,*.mkd,*.markdown call s:CheckIfGithub()

let g:gfm_syntax_enable_always = 0
let g:gfm_syntax_enable_filetypes = ['markdown.github']
```

**Comment by Th3Whit3Wolf** [comment]
I probably should of mention that this snippet is located in `ftplugin/markdown.vim`. That's why I use `autocmd BufEnter * call s:CheckIfGithub()`. That's a good point about using system. I suppose using something like [asyncrun](https://github.com/skywind3000/asyncrun.vim) would be the better route to go although git is very fast.

I'm not sure how I feel about changing the filetype. What is the benefit of changing the filetype?

**Comment by rhysd** [comment]
Running shell command asynchronously does not work. When the command is complete, syntax highlighting would have already been completed.

> I'm not sure how I feel about changing the filetype. What is the benefit of changing the filetype?

Please see `:help 'filetype'`. You can define new filetype by deriving existing one. Here you can define `markdown.github` whihc derives `markdown` filetype but it's only for GFM. Then vim-syntax-gfm can check the filetype and enable/disable its features by looking at the filetype value.
